version: '2.0'

#volumes:
#  data_replication:

networks:
  default:
    external:
      name: postgres_network

services:
  pg_db:
    build:
      context: .
      dockerfile: /opt/database/logical/PostgresSlave/postgresql
    container_name: PostgresSlavelogical
    image: postgres
    restart: always
#    user: "1002:1002"
#    privileged: true
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=postgres
      - POSTGRES_DB=stage
#      - PGDATA=/opt/database/logical/PostgresSlave/13
    volumes:
#      - pg_project:/opt/database/logical/PostgresSlave/13
      - ./data/:/var/lib/postgresql/data
      - /opt/database/logical/data_basebackup:/var/lib/postgresql/data_basebackup
    ports:
      - 5433:5432
